import '../styles/theme.css';
import '../styles/colors_and_type.css';
import '../styles/marketing.css';
// Self-hosted @font-face rules + the Geist preload. See app/fonts.js.
import { preloadFonts } from './fonts';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import { Analytics } from '@vercel/analytics/next';
import AcquisitionCapture from '../components/analytics/AcquisitionCapture';
import { THEME_BOOTSTRAP_SCRIPT } from '../src/lib/theme-bootstrap';

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://mcpemails.com';
// This value is generated in Google Search Console. It is public by design
// (Google verifies it from a meta tag), but is optional so local builds and
// preview deployments do not accidentally claim the production property.
const GOOGLE_SITE_VERIFICATION = process.env.GOOGLE_SITE_VERIFICATION;

export const metadata = {
  metadataBase: new URL(APP_URL),
  ...(GOOGLE_SITE_VERIFICATION
    ? { verification: { google: GOOGLE_SITE_VERIFICATION } }
    : {}),
  title: {
    default: 'Email MCP: Connect Gmail, Outlook & IMAP to Claude | mcpemails',
    template: '%s · mcpemails',
  },
  description: 'Connect Gmail, Outlook, Fastmail, iCloud, or any IMAP email to Claude, Cursor, ChatGPT, and MCP clients. Read, send, search, and organize email live.',
  openGraph: {
    type: 'website',
    siteName: 'mcpemails',
    title: 'Email MCP: Connect Gmail, Outlook & IMAP to Claude | mcpemails',
    description: 'Connect Gmail, Outlook, Fastmail, iCloud, or any IMAP email to Claude, Cursor, ChatGPT, and MCP clients. Read, send, search, and organize email live.',
    url: APP_URL,
    // Social card is generated by app/opengraph-image.tsx (Next.js file
    // convention); no explicit images entry needed here.
  },
  twitter: {
    // No `site`/`creator` handle: @mcpemails does not exist on X. Add it
    // back here if/when a real account is created.
    card: 'summary_large_image',
    title: 'Email MCP: Connect Gmail, Outlook & IMAP to Claude | mcpemails',
    description: 'Connect Gmail, Outlook, Fastmail, iCloud, or any IMAP email to Claude, Cursor, ChatGPT, and MCP clients. Read, send, search, and organize email live.',
  },
  // All three files live in public/ and are therefore served from the root.
  // The .ico is declared first with sizes="any" so modern browsers skip it and
  // pick the SVG below; it exists mainly because crawlers and directory sites
  // (Smithery, the Docker MCP catalog) fetch the literal /favicon.ico path and
  // fall back to a third-party favicon proxy when it 404s.
  // The mark is deliberately full-bleed (no rounded corners, no transparent
  // edge). Favicon proxies flatten onto white, so rounded corners came back as
  // white wedges on every dark-themed directory page; platforms that want a
  // rounded tile mask it themselves.
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any', type: 'image/x-icon' },
      { url: '/favicon.svg', type: 'image/svg+xml' },
    ],
    shortcut: '/favicon.ico',
    apple: { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default async function RootLayout({ children }) {
  preloadFonts();
  const locale = await getLocale();
  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        {/*
          Sets data-theme before first paint so a dark-theme visitor never sees
          a white flash. It carries no `nonce`: `script-src` allows it by the
          SHA-256 of THEME_BOOTSTRAP_SCRIPT (see src/lib/csp.ts), which the
          proxy computes from this same constant on every request.

          Do NOT inline the script text here, reformat it, or wrap the
          expression in anything that adds whitespace. The browser hashes the
          exact bytes React writes between the tags; one stray newline and the
          script is silently blocked, which shows up as a theme flash on every
          page and nothing else.
        */}
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP_SCRIPT }} />
      </head>
      <body>
        {/*
          Locale only, no messages. Messages given here are serialised into the
          HTML of EVERY route, and no route reads them from here: the marketing
          pages get theirs from the ClientMessages wrapper in app/[locale]/layout.tsx, the
          app and auth screens from AppLocaleProvider. `null` is explicit on
          purpose; leaving the prop out makes next-intl pass everything.
        */}
        <NextIntlClientProvider locale={locale} messages={null}>
          {children}
        </NextIntlClientProvider>
        <AcquisitionCapture />
        <Analytics />
      </body>
    </html>
  );
}
